/** Chromatic Cut page: a human, straightforward studio story with practical contact details. */
import { Link } from "wouter";
import { ArrowUpRight, CalendarHeart, MapPin, Phone, Sparkles } from "lucide-react";
import { PageEyebrow, SiteShell } from "@/components/SiteShell";
import { stylists } from "@/lib/salon-data";

export default function About() {
  return (
    <SiteShell>
      <section className="about-hero"><div className="page-rail" aria-hidden="true"><span>06 / ABOUT</span></div><div className="about-copy"><PageEyebrow>A different kind of salon calendar</PageEyebrow><h1>We make space for a <em>better conversation.</em></h1><p>Sable started with a simple belief: better hair is built through shared context. The right specialist, enough time, a clear plan — none of that should be hidden behind a generic booking button.</p><Link href="/book" className="primary-cta">Meet your next chair <ArrowUpRight size={17} /></Link></div><div className="about-image"><img src="/images/sable-salon-interior_5d74e433.jpg" alt="The airy, contemporary Sable salon interior" /><span className="about-image-caption">118 PINE STREET<br />SEATTLE, WA</span></div></section>
      <section className="studio-principles"><div><PageEyebrow>How we hold the room</PageEyebrow><h2>Personal, but never <em>precious.</em></h2></div><div className="principle-list"><article><span>01</span><h3>Expertise is a conversation.</h3><p>We explain the trade-offs, the maintenance, and the next best move — in plain language.</p></article><article><span>02</span><h3>Health makes the finish possible.</h3><p>Every significant color or texture decision starts with what the hair can actually support.</p></article><article><span>03</span><h3>Time is part of the service.</h3><p>Real work needs real appointment windows, so the booking system protects them from the start.</p></article></div></section>
      <section className="team-section"><div className="team-heading"><PageEyebrow>Meet the chairs</PageEyebrow><h2>Specialists with a <em>specific point of view.</em></h2></div><div className="team-grid">{stylists.map((stylist) => <article className="team-card" key={stylist.id}><div className="team-avatar" style={{ backgroundColor: stylist.accent }}>{stylist.initials}</div><p className="service-category">{stylist.role}</p><h3>{stylist.name}</h3><p>{stylist.bio}</p><span>{stylist.specialties.join(" · ")}</span></article>)}</div></section>
      <section className="contact-section"><div><PageEyebrow>Come by</PageEyebrow><h2>Find a little <em>time for you.</em></h2><p>118 Pine Street, Seattle, WA 98101<br />Tuesday–Friday 9–6 · Saturday–Sunday 10–5</p></div><div className="contact-actions"><a href="https://maps.google.com/?q=118+Pine+Street+Seattle+WA" target="_blank" rel="noreferrer" className="contact-action"><MapPin size={20} /><span><b>Directions</b><small>Open maps</small></span><ArrowUpRight size={17} /></a><a href="tel:+12065550198" className="contact-action"><Phone size={20} /><span><b>Call the studio</b><small>(206) 555-0198</small></span><ArrowUpRight size={17} /></a><Link href="/book" className="contact-action"><CalendarHeart size={20} /><span><b>Book online</b><small>Start an appointment plan</small></span><ArrowUpRight size={17} /></Link></div></section>
    </SiteShell>
  );
}
